title: Nathan's starter Github page 
author: NathanKrupa
theme: minima
email: your-email@domain.com
description: > # this means to ignore newlines until "baseurl:"
  I'm new to coding, but I've been writing for ages. This blog will tell the story of 
  how I learned how to program from scratch. 

# social links

github_username:  NathanKrupa

show_excerpts: false 
